name: Go run Code

on:
  push:
    branches:
      - wg-keys
      - github-actions

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.3'
      - name: run
        shell: bash
        env:
          TELEGRAM_APITOKEN: ${{ secrets.TELEGRAM_APITOKEN }}
          DNS_IPS:           ${{ secrets.DNS_IPS }}
          SERVER_PUB_KEY:    ${{ secrets.SERVER_PUB_KEY }}
          SERVER_ENDPOINT:   ${{ secrets.SERVER_ENDPOINT }}
          PUBLIC_INTERFACE:  ${{ secrets.PUBLIC_INTERFACE }}
          TEMPLATES_FOLDER:  ${{ secrets.TEMPLATES_FOLDER }}
        id: run
        run: sudo /usr/local/go/bin/go run cmd/wireguard-bot/main.go 
        continue-on-error: true

      - name: Check on failures
        if: steps.run.outcome != 'success' || steps.run.outcome != 'success'
        run: exit 1
