name: Go run Code

on:
  push:
    branches:
      - github-actions

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.3'
      - run: go run cmd/wireguard-bot/main.go