name: Go run Code

on:
  push:
    branches:
      - wg-keys

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.3'
      - shell: bash
        env:
          TELEGRAM_APITOKEN: ${{ secrets.TELEGRAM_APITOKEN }}
          DNS_IPS:           ${{ secrets.DNS_IPS }}
          SERVER_PUB_KEY:    ${{ secrets.SERVER_PUB_KEY }}
          SERVER_ENDPOINT:   ${{ secrets.SERVER_ENDPOINT }}
          PUBLIC_INTERFACE:  ${{ secrets.PUBLIC_INTERFACE }}
          TEMPLATES_FOLDER:  ${{ secrets.TEMPLATES_FOLDER }}

        run: sudo /usr/local/go/bin/go run cmd/wireguard-bot/main.go
